stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - ./data\raw  # Fixed path with forward slash and trailing slash

  pre_processing:
    cmd: python src/pre_processing.py
    deps:
      - ./data\raw
      - src/pre_processing.py
    outs:
      - ./data\interim

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - ./data\interim
      - src/feature_engineering.py  # Fixed indentation
    outs:
      - ./data\processed

  model_building:
    cmd: python src/model_building.py
    deps:
      - ./data\processed
      - src/model_building.py
    outs:
      - ./model\model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - ./model\model.pkl
      - src/model_evaluation.py
    outs:
      - ./reports\matrix.json